### ISSUE TITLE
根目录再后退，程序就不能继续操作了:(

### ISSUE THREAD

**Issue by wzytim** [ExerciseBook/XLXsFTP#3]
![image](https://user-images.githubusercontent.com/53875091/88945410-8a0ec900-d2c0-11ea-972b-2940a9703514.png)

**Comment by ExerciseBook** [comment]
自己重新输路径。上面的编辑框可以随便改的。

**Comment by ExerciseBook** [comment]
自己重新输路径。上面的编辑框可以随便改的。
